baseURL = "https://conmeobayvaodutru.com/"
languageCode = "vi"
title = "Con Mèo Bay Vào Dũ Trụ"
buildDrafts = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"
  series = "series"
